import {
  Activity,
  CalendarCheck,
  CalendarDays,
  Cake,
  CircleDashed,
  CircleDot,
  Candy,
  Droplet,
  FileText,
  Footprints,
  Gauge,
  Grip,
  HeartCrack,
  HeartPulse,
  Hexagon,
  NotebookPen,
  Orbit,
  RefreshCw,
  Scale,
  ScanLine,
  Shrink,
  Sparkles,
  Spline,
  Square,
  Stethoscope,
  TestTube,
  TrendingDown,
  TrendingUp,
  User,
  Waypoints,
  type LucideIcon,
} from 'lucide-react'
import type { PatientIcon } from '@/types'

/** The dataset config names icons; this maps each name to its lucide glyph (always drawn at 1.5px). */
export const PATIENT_ICONS: Record<PatientIcon, LucideIcon> = {
  user: User,
  cake: Cake,
  gauge: Gauge,
  'heart-crack': HeartCrack,
  activity: Activity,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'heart-pulse': HeartPulse,
  footprints: Footprints,
  'scan-line': ScanLine,
  waypoints: Waypoints,
  droplet: Droplet,
  candy: Candy,
  'circle-dot': CircleDot,
  'circle-dashed': CircleDashed,
  square: Square,
  grip: Grip,
  spline: Spline,
  shrink: Shrink,
  hexagon: Hexagon,
  sparkles: Sparkles,
  scale: Scale,
  orbit: Orbit,
  'calendar-days': CalendarDays,
  'calendar-check': CalendarCheck,
  'file-text': FileText,
  'test-tube': TestTube,
  'notebook-pen': NotebookPen,
  stethoscope: Stethoscope,
  'refresh-cw': RefreshCw,
}
